#!/bin/sh -e
trap 'RESULT=$?; rm -f $$.out $$.c; exit $RESULT' HUP INT TERM QUIT EXIT
touch $$.c

HEADERS=''
NON_ARGS=''

while [ -n "$1" ]; do
  case "$1" in
  -h) shift; HEADERS="$HEADERS $1" ;;
  -h*) HEADERS="$HEADERS $(echo "$1" | sed 's/^-h=*//')" ;;
  *) NON_ARGS="$NON_ARGS $1" ;;
  esac
  shift
done

for HEADER in $HEADERS; do
  echo "#include \"$HEADER\"" >> $$.c
done 

echo "int main() { return(!($NON_ARGS)); }" >> $$.c 

scripts/compile -o $$.out $$.c
./$$.out
